<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWImG8Nx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWImG8Nx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWImG8Nx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWImG8Nx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWImG8Nx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WImG8Nx',
    'container.build_id' => '375d908b',
    'container.build_time' => 1603885281,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWImG8Nx');
