<?php

namespace ContainerKH0rxh0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEasyadmin_Filter_Type_TextareaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'easyadmin.filter.type.textarea' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Form\Filter\Type\TextFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\form\\AbstractType.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\easycorp\\easyadmin-bundle\\src\\Form\\Filter\\Type\\TextFilterType.php';

        return $container->privates['easyadmin.filter.type.textarea'] = new \EasyCorp\Bundle\EasyAdminBundle\Form\Filter\Type\TextFilterType('Symfony\\Component\\Form\\Extension\\Core\\Type\\TextareaType');
    }
}
