<?php

namespace ContainerWImG8Nx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCron_ResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cron.resolver' shared service.
     *
     * @return \Cron\CronBundle\Cron\Resolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\cron\\cron\\src\\Resolver\\ResolverInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\cron\\cron-bundle\\Cron\\Resolver.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\cron\\cron-bundle\\Cron\\CommandBuilder.php';

        return $container->services['cron.resolver'] = new \Cron\CronBundle\Cron\Resolver(($container->services['cron.manager'] ?? $container->load('getCron_ManagerService')), new \Cron\CronBundle\Cron\CommandBuilder('dev'), \dirname(__DIR__, 4));
    }
}
