<?php

namespace ContainerWImG8Nx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewVisitCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\NewVisitCommand' shared autowired service.
     *
     * @return \App\Command\NewVisitCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\console\\Command\\Command.php';
        include_once \dirname(__DIR__, 4).'\\src\\Command\\NewVisitCommand.php';

        $container->privates['App\\Command\\NewVisitCommand'] = $instance = new \App\Command\NewVisitCommand(($container->privates['App\\Repository\\ShowVisitRepository'] ?? $container->load('getShowVisitRepositoryService')), ($container->services['swiftmailer.mailer.default'] ?? $container->load('getSwiftmailer_Mailer_DefaultService')));

        $instance->setName('app:visit-reminder');

        return $instance;
    }
}
