<?php

namespace ContainerWImG8Nx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Logout_Listener_LegacySuccessListener_MainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.logout.listener.legacy_success_listener.main' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-bundle\\Security\\LegacyLogoutHandlerListener.php';

        return $container->privates['security.logout.listener.legacy_success_listener.main'] = new \Symfony\Bundle\SecurityBundle\Security\LegacyLogoutHandlerListener(($container->services['App\\Controller\\SecurityController'] ?? $container->load('getSecurityControllerService')));
    }
}
